name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: install depends
      run: sudo apt install -y libcppunit-dev libalut-dev libsdl1.2-dev freeglut3-dev libglew-dev
    - name: make
      run: make all
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*,data/*"
        token: ${{ secrets.GITHUB_TOKEN }}